<?php
//$Id$

/* 
 * @file
 * Provides a content type that publishes nodes to Layar for display through
 * augmented reality apps.
 */

function layar_node_info() {
  return array(
    'layar_node' => array(
      'name' => t('Layar Node'),
      'module' => 'drupal_layars',
      'description' => t('Implementation of a content type in Drupal that publishes to Layar.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
      'has_body' => TRUE,
      'body_label' => t('Body'),
      'min_word_count' => 2,
      'locked' => FALSE,
    )
  );
}

?>
